services:
  whispy_debug_builder: # Debug build container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - CMAKE_BUILD_TYPE=Debug
      - CMAKE_BUILD_DIR=cmake-dev-build
      - CMAKE_CXX_COMPILER=/usr/local/bin/g++

  whispy_deploy_builder: # Release build container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - CMAKE_BUILD_TYPE=Release
      - CMAKE_BUILD_DIR=cmake-build
      - CMAKE_CXX_COMPILER=/usr/local/bin/g++