services:
  whisperpy_dev_build: # Testing build container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - WHISPERPY_CMAKE_BUILD_TYPE=Debug
      - WHISPERPY_CMAKE_BUILD_DIR=/app/cmake-dev-build

  whisper_test: # Testing container
    image: python:latest
    command: sh -c "./tests/runall.sh"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - WHISPERPY_LIBRARY_MODE=Development
  
  whisperpy_deploy_build: # Release build container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - WHISPERPY_CMAKE_BUILD_TYPE=Release
      - WHISPERPY_CMAKE_BUILD_DIR=/app/cmake-build