services:
  whisperpy_dev_builder: # Testing build container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - WHISPERPY_CMAKE_BUILD_TYPE=Debug
      - WHISPERPY_CMAKE_BUILD_DIR=cmake-dev-build
      - WHISPERPY_CMAKE_CXX_COMPILER=/usr/local/bin/g++

  whisperpy_tester: # Testing container
    build:
      context: .
      dockerfile: ./Dockerfile.tester
    volumes:
      - .:/app
    environment:
      - WHISPERPY_LIBRARY_MODE=Development
  
  whisperpy_deploy_builder: # Release build container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - WHISPERPY_CMAKE_BUILD_TYPE=Release
      - WHISPERPY_CMAKE_BUILD_DIR=cmake-build
      - WHISPERPY_CMAKE_CXX_COMPILER=/usr/local/bin/g++